import { Listing } from '@/types';

const wDefaults = { content: '', address: '', phone: '', operating_hours: '', menu_items: [] as any[], notes: '' };

export const sampleListings: Listing[] = [
  /* ─── 🍽️ RESTAURANT 1: Gwangjang Market ─── */
  {
    id: '1',
    slug: 'gwangjang-market-food-tour',
    category: 'restaurants',
    subcategory: 'korean-food',
    city: 'seoul',
    title: 'Gwangjang Market Food Tour',
    description: 'Experience the oldest traditional market in Seoul. Taste bindaetteok, mayak gimbap, and more authentic Korean street food from vendors who have been serving for decades.',
    content: 'Gwangjang Market has been Seoul\'s beating culinary heart since 1905. Walking through the narrow aisles, you\'ll be greeted by the sizzle of cast-iron griddles and the irresistible aroma of freshly fried mung bean pancakes.\n\nOur curated food tour introduces you to the market\'s legendary stalls — some run by third-generation vendors who\'ve perfected their recipes over 60 years. From the addictive mini gimbap rolls (nicknamed "mayak" meaning "drug" for their addictive taste) to the silky raw beef tartare (yukhoe), every bite tells a story of Korean food heritage.\n\nThe tour also visits the hidden knife-cut noodle alley and the vibrant textile section upstairs, offering a complete picture of this living cultural landmark.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    price: 35,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 234,
    tags: ['HOT', 'Traditional'],
    featured: true,
    address: '88 Changgyeonggung-ro, Jongno-gu, Seoul',
    phone: '+82-2-2267-0291',
    operating_hours: 'Mon–Sat 09:00–23:00, Sun 09:00–22:00',
    menu_items: [
      { category: 'main', name: 'Bindaetteok (Mung Bean Pancake)', price: 5000, description: 'Crispy and savory, served fresh off the griddle' },
      { category: 'main', name: 'Yukhoe (Raw Beef Tartare)', price: 15000, description: 'Premium Korean-style steak tartare with pear' },
      { category: 'main', name: 'Kalguksu (Knife-Cut Noodles)', price: 8000, description: 'Handmade noodles in rich anchovy broth' },
      { category: 'main', name: 'Tteokbokki (Spicy Rice Cakes)', price: 4000, description: 'Classic street-style with fish cake' },
      { category: 'main', name: 'Sundae (Korean Blood Sausage)', price: 5000, description: 'Steamed with glass noodle filling' },
      { category: 'side', name: 'Mayak Gimbap (Mini Rice Rolls)', price: 3000, description: '10 bite-sized rolls with sesame oil dip' },
      { category: 'side', name: 'Japchae (Glass Noodles)', price: 7000, description: 'Sweet potato noodles with vegetables' },
      { category: 'side', name: 'Kimchi Jeon (Kimchi Pancake)', price: 6000, description: 'Crispy fermented cabbage pancake' },
      { category: 'side', name: 'Odeng (Fish Cake Skewers)', price: 1000, description: 'Served with warm anchovy broth' },
      { category: 'side', name: 'Twigim (Fried Assortment)', price: 3000, description: 'Sweet potato, shrimp, vegetables' },
      { category: 'drink', name: 'Makgeolli (Rice Wine)', price: 5000, description: 'Traditional unfiltered rice wine' },
      { category: 'drink', name: 'Soju', price: 4000, description: 'Classic Korean spirit' },
      { category: 'drink', name: 'Sikhye (Sweet Rice Drink)', price: 2000, description: 'Non-alcoholic traditional dessert drink' },
      { category: 'drink', name: 'Korean Beer (Cass/Kloud)', price: 4000, description: 'Draft 500ml' },
      { category: 'drink', name: 'Banana Milk', price: 1500, description: 'Korea\'s iconic banana-flavored milk' },
    ],
    notes: JSON.stringify({
      __plain: 'Popular with tourists. Best visited before 11am to avoid crowds.',
      __extra: {
        booking_deposit: 30000,
        dietary: { vegetarian: false, pescetarian: false, halal: false, gluten_free: false, non_dairy: false },
        naver_map_url: 'https://naver.me/FYfYFYfY',
        kakao_map_url: 'https://place.map.kakao.com/7858097',
        google_map_url: 'https://maps.google.com/?q=Gwangjang+Market+Seoul',
        break_time: 'No break time',
        holidays: 'Sundays (some stalls), Lunar New Year & Chuseok',
        reservation_notices: [
          'Walk-in only — no reservations accepted at market stalls',
          'Best visited before 11:00 AM or after 3:00 PM to avoid peak crowds',
          'Bring cash — many stalls do not accept cards',
          'Expect shared seating at communal benches',
          'English menus available at most stalls — look for picture menus',
        ],
        cancellation_policy: [
          'Tour bookings can be cancelled for a full refund up to 48 hours before the tour',
          'Cancellations within 24–48 hours receive a 50% refund',
          'No refund for cancellations within 24 hours or no-shows',
          'Weather-related cancellations will be rescheduled at no cost',
        ],
        important_notes: [
          'Wear comfortable shoes — the market floor can be slippery',
          'The market can be very crowded on weekends and holidays',
          'Some vendors may not speak English — our guide will help translate',
          'Food allergies: please inform your guide before the tour begins',
          'Photography is welcome but always ask vendors before taking close-up photos',
          'The market has limited seating — be prepared to eat standing at some stalls',
          'Restrooms are located on the 2nd floor (bring your own tissue)',
          'Keep your belongings secure in crowded areas',
          'Last food orders are typically 1 hour before closing',
          'Subway: Line 1 Jongno 5-ga Station, Exit 8 (2 min walk)',
        ],
        external_reviews: [
          { source: 'Google', reviewer: 'Sarah M.', rating: 5, text: 'Absolutely incredible food tour! The bindaetteok was the best thing I\'ve ever eaten. Our guide was so knowledgeable about the market\'s history.', date: '2026-04-20' },
          { source: 'TripAdvisor', reviewer: 'James L.', rating: 4, text: 'Great experience overall. The market was busy but our guide navigated it perfectly. The mayak gimbap lives up to its name — truly addictive!', date: '2026-04-15' },
          { source: 'Naver', reviewer: '여행자김', rating: 5, text: '외국인 친구와 함께 갔는데 영어 메뉴가 잘 되어있어서 좋았습니다. 빈대떡 맛집은 정말 최고!', date: '2026-03-28' },
        ],
      },
    }),
  },

  /* ─── 🍽️ RESTAURANT 2: Gangnam BBQ ─── */
  {
    id: '2',
    slug: 'gangnam-korean-bbq',
    category: 'restaurants',
    subcategory: 'korean-bbq',
    city: 'seoul',
    title: 'Premium Hanwoo BBQ in Gangnam',
    description: 'Savor the finest Korean beef at a top-rated Gangnam BBQ restaurant. Premium 1++ grade Hanwoo with expert grilling service and 12 banchan side dishes.',
    content: 'This is not your average Korean BBQ. Located in the heart of Gangnam, this restaurant specializes in 1++ grade Hanwoo — the highest quality Korean beef, known for its exceptional marbling and melt-in-your-mouth texture.\n\nYour experience begins with a curated banchan spread of 12 seasonal side dishes, followed by a premium meat course. The staff will expertly grill each cut to perfection over premium charcoal and guide you on the best way to enjoy each piece.\n\nThe restaurant features both open seating and private rooms, making it perfect for both intimate dinners and group celebrations. Complimentary digestif (soju or plum wine) is served after the meal.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    price: 65,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 189,
    tags: ['BEST', 'Premium'],
    featured: true,
    address: '23 Teheran-ro 8-gil, Gangnam-gu, Seoul',
    phone: '+82-2-555-1234',
    operating_hours: 'Daily 11:30–22:00 (Last order 21:00)',
    menu_items: [
      { category: 'main', name: 'Hanwoo Sirloin Set (200g)', price: 89000, description: '1++ grade premium sirloin with banchan set' },
      { category: 'main', name: 'Chadolbaegi (Brisket)', price: 25000, description: 'Thinly sliced, cooks in seconds on the grill' },
      { category: 'main', name: 'Ggotsal (Ribeye Cap)', price: 45000, description: 'Rich marbling, charcoal grilled to perfection' },
      { category: 'main', name: 'Galbi (Short Ribs)', price: 55000, description: 'Marinated in house soy sauce for 24 hours' },
      { category: 'main', name: 'Samgyeopsal (Pork Belly)', price: 16000, description: 'Thick-cut premium pork belly' },
      { category: 'side', name: 'Naengmyeon (Cold Noodles)', price: 12000, description: 'Perfect finisher after BBQ — icy buckwheat noodles' },
      { category: 'side', name: 'Doenjang Jjigae', price: 8000, description: 'Soybean paste stew with tofu' },
      { category: 'side', name: 'Steamed Egg (Gyeran Jjim)', price: 5000, description: 'Fluffy Korean steamed egg casserole' },
      { category: 'side', name: 'Cheese Corn', price: 6000, description: 'Buttery sweet corn with melted mozzarella' },
      { category: 'side', name: 'Kimchi Fried Rice', price: 9000, description: 'Made with aged kimchi on the grill' },
      { category: 'drink', name: 'Soju (Chamisul)', price: 5000, description: 'Classic Korean soju, pairs perfectly with BBQ' },
      { category: 'drink', name: 'Korean Beer (Draft)', price: 6000, description: 'Cass or Kloud 500ml' },
      { category: 'drink', name: 'Somaek (Soju + Beer)', price: 9000, description: 'The iconic Korean cocktail combo' },
      { category: 'drink', name: 'Plum Wine', price: 8000, description: 'Sweet Korean maesil wine (300ml)' },
      { category: 'drink', name: 'Soft Drinks', price: 3000, description: 'Coke, Sprite, or Chilsung Cider' },
    ],
    notes: JSON.stringify({
      __plain: 'Reservation highly recommended for dinner. Private rooms available for 6+ guests.',
      __extra: {
        booking_deposit: 50000,
        dietary: { vegetarian: false, pescetarian: false, halal: false, gluten_free: true, non_dairy: true },
        naver_map_url: 'https://naver.me/xAbCdEfG',
        kakao_map_url: 'https://place.map.kakao.com/12345678',
        google_map_url: 'https://maps.google.com/?q=Gangnam+Korean+BBQ+Seoul',
        break_time: '15:00–17:00 (weekdays only)',
        holidays: 'Every 1st and 3rd Monday',
        reservation_notices: [
          'Online booking requires a ₩50,000 deposit per party (applied to your bill)',
          'Reservations accepted up to 30 days in advance',
          'Private rooms available for groups of 6 or more (advance booking required)',
          'Please arrive within 15 minutes of your reservation time',
          'For parties of 8+, a set menu must be pre-selected',
        ],
        cancellation_policy: [
          'Full refund if cancelled 24+ hours before reservation',
          'No refund for cancellations within 24 hours',
          'No-shows will forfeit the full deposit',
          'Deposit is non-transferable to other dates',
        ],
        important_notes: [
          'Staff will grill all meat for you — no self-grilling',
          'Dress code: smart casual (no flip-flops or sleeveless)',
          'Children under 7 eat free (kids banchan set included)',
          'Free valet parking available at building B1',
          'Allergies: please inform staff before ordering',
          'All meat is certified 1++ Korean Hanwoo with origin certificate',
          'Tipping is not expected in Korea',
          'Wi-Fi available: Password on your table card',
        ],
        external_reviews: [
          { source: 'Google', reviewer: 'Mike T.', rating: 5, text: 'Best Korean BBQ I\'ve ever had. The Hanwoo melts in your mouth. Staff grills everything perfectly. Worth every penny.', date: '2026-04-10' },
          { source: 'MangoPlate', reviewer: '맛집탐험가', rating: 5, text: '한우 품질이 정말 최상급입니다. 직원분들이 직접 구워주셔서 편하게 먹을 수 있어요.', date: '2026-03-22' },
          { source: 'TripAdvisor', reviewer: 'Emma K.', rating: 4, text: 'Amazing quality meat! The private room was great for our group. Only minus: a bit pricey, but you get what you pay for.', date: '2026-03-05' },
        ],
      },
    }),
  },

  /* ─── ✨ WELLNESS: Skin Clinic ─── */
  {
    id: '5',
    slug: 'gangnam-skin-clinic',
    category: 'wellness',
    subcategory: 'skin-clinic',
    city: 'seoul',
    title: 'Gangnam Premium Dermatology Clinic',
    description: 'Get world-class skin treatments at Korea\'s most renowned dermatology clinic. Consultation included with English-speaking dermatologists.',
    content: 'Korea is the global capital of skincare, and this Gangnam clinic represents the pinnacle of K-beauty dermatology. Your visit begins with an AI-powered skin analysis, followed by a one-on-one consultation with a board-certified dermatologist.\n\nPopular treatments include hydrafacial, laser toning, and the signature "Glass Skin" package. Post-treatment care instructions are provided in English.',
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&q=80',
    price: 120, currency: 'USD', rating: 4.9, reviewCount: 312,
    tags: ['BEST', 'Premium'], featured: true,
    address: '412 Gangnam-daero, Gangnam-gu, Seoul (3F)',
    phone: '+82-2-512-8800',
    operating_hours: 'Mon–Fri 10:00–19:00, Sat 10:00–16:00',
    menu_items: [
      { name: 'Glass Skin Package', price: 250000, description: 'Micro-needling + Growth Factor (90 min)' },
      { name: 'Hydrafacial Premium', price: 180000, description: 'Deep cleansing + hydration (60 min)' },
      { name: 'Laser Toning', price: 150000, description: 'Even skin tone + pore tightening (45 min)' },
    ],
    notes: JSON.stringify({ __plain: '', __extra: { reservation: 'Required', english_staff: true, gender_policy: 'All welcome', duration: '60–120 minutes', what_to_bring: 'Come with clean face, no makeup.' } }),
  },

  /* ─── 🎯 ACTIVITY: Cooking Class ─── */
  {
    id: '9',
    slug: 'korean-cooking-class',
    category: 'activities',
    subcategory: 'cooking-classes',
    city: 'seoul',
    title: 'Learn to Make Kimchi & Bibimbap',
    description: 'Hands-on Korean cooking class in a traditional kitchen. Learn to make kimchi, bibimbap, and Korean pancakes from a local chef.',
    content: 'Led by Chef Minji with 20 years of experience. Start with a market tour, then cook 3 iconic Korean dishes. Dietary accommodations available.',
    image: 'https://images.unsplash.com/photo-1583224994076-0a5a4e3384c7?w=800&q=80',
    price: 55, currency: 'USD', rating: 4.9, reviewCount: 178,
    tags: ['BEST'], featured: true,
    address: '15 Insadong-gil, Jongno-gu, Seoul (B1)',
    phone: '+82-10-1234-5678', operating_hours: '',
    menu_items: [
      { name: 'Standard Class (3 hrs)', price: 55000, description: 'Market tour + 3 dishes + meal' },
      { name: 'Premium Class (4 hrs)', price: 85000, description: 'Adds tteokbokki + makgeolli pairing' },
    ],
    notes: JSON.stringify({ __plain: '', __extra: { duration: '3–4 hours', group_size: 'Max 8 people', difficulty: 'Easy', inclusions: 'All ingredients, apron, recipe booklet', what_to_bring: 'Nothing needed', meeting_point: '15 Insadong-gil B1 — red door with MUGOONG sign', english_guide: true } }),
  },

  /* ─── 💡 TIPS ─── */
  {
    id: '13',
    slug: 'seoul-metro-guide',
    category: 'tips-and-trend',
    subcategory: 'public-transportation',
    city: 'seoul',
    title: 'How to Use the Seoul Metro Like a Local',
    description: 'Everything you need to know about navigating Seoul\'s subway system — from buying T-money cards to transferring between lines.',
    content: 'Seoul\'s metro system is one of the best in the world.\n\n🎫 Getting a T-money Card\nBuy at any convenience store for ₩2,500. Each ride costs ₩1,250.\n\n📱 Must-Have Apps\n• Naver Map — Best for Korean transit\n• KakaoMetro — Real-time arrivals\n\n🚇 Pro Tips\n• Rush hour: 7:30–9:00 and 17:30–19:00\n• Free Wi-Fi on all trains\n• Pink seats are priority seats — always leave them empty',
    image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&q=80',
    price: 0, currency: 'USD', rating: 0, reviewCount: 0,
    tags: ['Guide', 'Essential'], featured: false,
    address: '', phone: '', operating_hours: '', menu_items: [], notes: '',
  },
];
