import { Listing } from '@/types';

export const sampleListings: Listing[] = [
  {
    id: '1',
    slug: 'gwangjang-market-food-tour',
    category: 'restaurants',
    subcategory: 'korean-food',
    contentType: 'product',
    city: 'seoul',
    title: 'Gwangjang Market Food Tour',
    description: 'Experience the oldest traditional market in Seoul with a guided tasting route through iconic Korean street food stalls.',
    content: 'Walk through Gwangjang Market with a local host who knows which stalls are worth your time and money.\n\nThis food-focused route is ideal for first-time visitors who want a low-pressure way to try classic Korean dishes in one place.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    price: 35,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 234,
    tags: ['HOT', 'Traditional'],
    featured: true,
  },
  {
    id: '2',
    slug: 'gangnam-korean-bbq',
    category: 'restaurants',
    subcategory: 'korean-bbq',
    contentType: 'product',
    city: 'seoul',
    title: 'Premium Hanwoo BBQ in Gangnam',
    description: 'Savor premium Korean beef in Gangnam with a curated set menu designed for international visitors.',
    content: 'This reservation pairs top-grade Hanwoo with an approachable dining flow, so travelers can enjoy Korean BBQ without guessing what to order.\n\nThe restaurant team is used to overseas guests and the setting works well for dates, small groups, and business travelers.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    price: 65,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 189,
    tags: ['BEST', 'Premium'],
    featured: true,
  },
  {
    id: '3',
    slug: 'hongdae-fried-chicken',
    category: 'restaurants',
    subcategory: 'korean-fried-chicken',
    contentType: 'product',
    city: 'seoul',
    title: 'Hongdae Fried Chicken & Beer Night',
    description: 'Enjoy a classic chimaek night in Hongdae with crispy fried chicken, Korean beer, and a social local atmosphere.',
    content: 'This listing is built for visitors who want a reliable first Korean fried chicken stop without spending half the night comparing options.\n\nIt works especially well for solo travelers and friends staying around Hongdae or Sinchon.',
    image: 'https://images.unsplash.com/photo-1575932444877-5106bee2a599?w=800&q=80',
    price: 28,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 156,
    tags: ['HOT'],
    featured: false,
  },
  {
    id: '4',
    slug: 'itaewon-cocktail-bar',
    category: 'restaurants',
    subcategory: 'bars',
    contentType: 'product',
    city: 'seoul',
    title: 'Hidden Speakeasy Bar in Itaewon',
    description: 'Discover a tucked-away cocktail bar in Itaewon serving Korean-inspired drinks in an intimate setting.',
    content: 'This is a strong fit for travelers looking for a polished evening spot that still feels local.\n\nThe bar menu leans creative without being intimidating, and the staff are comfortable with international guests.',
    image: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80',
    price: 45,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 98,
    tags: ['NEW'],
    featured: true,
  },
  {
    id: '5',
    slug: 'gangnam-skin-clinic',
    category: 'wellness',
    subcategory: 'skin-clinic',
    contentType: 'product',
    city: 'seoul',
    title: 'Gangnam Premium Dermatology Clinic',
    description: 'Book a premium skin clinic consultation in Gangnam with visitor-friendly guidance and treatment planning.',
    content: 'Many overseas guests feel overwhelmed by the number of Korean skin clinics online.\n\nThis listing is designed as a trusted entry point, with clear expectations around consultation, treatment style, and aftercare.',
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&q=80',
    price: 120,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 312,
    tags: ['BEST', 'Premium'],
    featured: true,
  },
  {
    id: '6',
    slug: 'hongdae-hair-salon',
    category: 'wellness',
    subcategory: 'hair-salon',
    contentType: 'product',
    city: 'seoul',
    title: 'K-Style Hair Makeover in Hongdae',
    description: 'Refresh your look at a Hongdae salon popular for Korean trend cuts and visitor-friendly consultations.',
    content: 'Ideal for travelers who want a style update while in Korea without language stress.\n\nThe consultation process is simple and the team can guide guests through inspiration photos, maintenance, and add-on services.',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
    price: 80,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 267,
    tags: ['HOT'],
    featured: true,
  },
  {
    id: '7',
    slug: 'dragon-hill-spa',
    category: 'wellness',
    subcategory: 'sauna',
    contentType: 'product',
    city: 'seoul',
    title: 'Dragon Hill Spa Jjimjilbang Experience',
    description: 'Try the classic Korean jjimjilbang experience with sauna rooms, pools, and rest zones in one visit.',
    content: 'A jjimjilbang can be confusing if it is your first time in Korea.\n\nThis entry makes the format easier to understand, from check-in to locker use, bathing etiquette, and what to expect in the common areas.',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80',
    price: 25,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 421,
    tags: ['Popular'],
    featured: false,
  },
  {
    id: '8',
    slug: 'bukchon-hanok-tour',
    category: 'activities',
    subcategory: 'traditional-cultural-tours',
    contentType: 'product',
    city: 'seoul',
    title: 'Bukchon Hanok Village Walking Tour',
    description: 'Explore Bukchon with a guided route that blends architecture, local history, and cultural etiquette.',
    content: 'This tour is designed for travelers who want a more meaningful visit than simply taking photos in the alleys.\n\nIt includes context around the neighborhood, respectful visiting tips, and moments that make sense for short-stay travelers.',
    image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&q=80',
    price: 40,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 345,
    tags: ['Cultural', 'HOT'],
    featured: true,
  },
  {
    id: '9',
    slug: 'korean-cooking-class',
    category: 'activities',
    subcategory: 'cooking-classes',
    contentType: 'product',
    city: 'seoul',
    title: 'Learn to Make Kimchi & Bibimbap',
    description: 'Join a hands-on cooking class and learn two iconic Korean dishes in a welcoming local kitchen.',
    content: 'This class works well for first-time visitors, couples, and solo travelers who want a social activity with a clear takeaway.\n\nThe recipes are approachable enough to recreate after your trip, and the host explains ingredients in a traveler-friendly way.',
    image: 'https://images.unsplash.com/photo-1583224994076-0a5a4e3384c7?w=800&q=80',
    price: 55,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 178,
    tags: ['BEST'],
    featured: true,
  },
  {
    id: '10',
    slug: 'haeundae-seafood',
    category: 'restaurants',
    subcategory: 'korean-food',
    contentType: 'product',
    city: 'busan',
    title: 'Haeundae Fresh Seafood Market Tour',
    description: 'Taste Busan seafood with a guided market route built for short-stay travelers.',
    content: 'This experience removes the friction from choosing a seafood spot in a market setting.\n\nIt is especially useful for travelers who want freshness and local character but do not want to navigate the ordering process alone.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    price: 42,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 201,
    tags: ['HOT', 'Busan'],
    featured: true,
  },
  {
    id: '11',
    slug: 'jeju-black-pork',
    category: 'restaurants',
    subcategory: 'korean-bbq',
    contentType: 'product',
    city: 'jeju',
    title: 'Jeju Black Pork BBQ Experience',
    description: 'Try Jeju black pork at a locally loved BBQ spot with a traveler-ready set menu.',
    content: 'Jeju black pork is one of the island\'s signature foods, but the experience varies a lot by venue.\n\nThis listing focuses on reliable quality, good location flow, and an easy-to-understand BBQ setup for visitors.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    price: 50,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 143,
    tags: ['Jeju Special'],
    featured: true,
  },
  {
    id: '12',
    slug: 'jeonju-bibimbap',
    category: 'restaurants',
    subcategory: 'korean-food',
    contentType: 'product',
    city: 'jeonju',
    title: 'Authentic Jeonju Bibimbap Experience',
    description: 'Taste Jeonju bibimbap close to its birthplace with a curated dining recommendation for travelers.',
    content: 'Jeonju has no shortage of bibimbap options, which makes first-time choice harder rather than easier.\n\nThis listing gives visitors a clear starting point and pairs the meal with neighborhood context around the hanok village area.',
    image: 'https://images.unsplash.com/photo-1583224994076-0a5a4e3384c7?w=800&q=80',
    price: 20,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 267,
    tags: ['BEST', 'Must-Try'],
    featured: true,
  },
  {
    id: '13',
    slug: 'seoul-travel-tips-first-timers',
    category: 'tips-and-trend',
    subcategory: 'travel-tips',
    contentType: 'article',
    city: 'seoul',
    title: 'Seoul Travel Tips for First-Time Visitors',
    description: 'A practical guide to getting around Seoul smoothly, from payment basics to neighborhood planning.',
    content: 'If this is your first Korea trip, Seoul can feel easy and overwhelming at the same time.\n\nThe city is safe and convenient, but small friction points add up fast: transit cards, payment expectations, map apps, late-night transport, and how neighborhoods are actually experienced on foot.\n\nThis guide covers the basics that save the most time during a short stay, especially for travelers trying to balance food, shopping, and local experiences without overplanning every hour.',
    image: 'https://images.unsplash.com/photo-1538485399081-7c897a2f77c3?w=800&q=80',
    price: 0,
    currency: 'USD',
    rating: 0,
    reviewCount: 0,
    tags: ['Guide'],
    featured: false,
  },
  {
    id: '14',
    slug: 'korea-trend-now-cafes-fashion',
    category: 'tips-and-trend',
    subcategory: 'trend-now',
    contentType: 'article',
    city: 'seoul',
    title: 'What Is Trending in Korea Right Now',
    description: 'A quick editorial snapshot of current Korea trends in cafes, beauty, retail, and neighborhood culture.',
    content: 'Trend-focused travelers usually do not want a museum version of Korea. They want to know what people are actually into now.\n\nThis CMS-style piece is built for that purpose: recent cafe concepts, beauty service patterns, shopping zones, and local lifestyle trends that help visitors decide where to spend time.\n\nIt works best as an editorial article rather than a bookable product, so the page stays focused on reading instead of reservations.',
    image: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800&q=80',
    price: 0,
    currency: 'USD',
    rating: 0,
    reviewCount: 0,
    tags: ['Editorial'],
    featured: false,
  },
  {
    id: '15',
    slug: 'seoul-smoking-spots-guide',
    category: 'tips-and-trend',
    subcategory: 'smoking-spots',
    contentType: 'article',
    city: 'seoul',
    title: 'Smoking Spots in Seoul: What Travelers Should Know',
    description: 'A practical etiquette guide to smoking rules, designated zones, and what visitors should avoid in Seoul.',
    content: 'Smoking etiquette in Korea can be confusing because expectations differ by street, building, and district.\n\nThis article is better handled as reference content than a product listing. It helps travelers understand where designated smoking areas are likely to exist, when indoor policies are strict, and how to avoid common mistakes.\n\nIt can also support neighborhood-specific content later as your CMS grows.',
    image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&q=80',
    price: 0,
    currency: 'USD',
    rating: 0,
    reviewCount: 0,
    tags: ['Guide'],
    featured: false,
  },
  {
    id: '16',
    slug: 'airport-express-and-tmoney-starter',
    category: 'tips-and-trend',
    subcategory: 'public-transportation',
    contentType: 'product',
    city: 'seoul',
    title: 'Airport Express + T-money Starter Pickup',
    description: 'A simple transportation starter option for travelers arriving in Seoul who want to move fast from day one.',
    content: 'Transportation is the one area inside Tips & Trend that still behaves like a sellable service.\n\nThis kind of entry can bundle airport rail access, a transit card starter package, or arrival guidance, so it stays in the product flow with pricing and booking-style details.',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    price: 18,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 84,
    tags: ['Arrival'],
    featured: false,
  },
];
