import { Listing } from '@/types';

export const sampleListings: Listing[] = [
  {
    id: '1',
    slug: 'gwangjang-market-food-tour',
    category: 'restaurants',
    subcategory: 'korean-food',
    city: 'seoul',
    title: 'Gwangjang Market Food Tour',
    description: 'Experience the oldest traditional market in Seoul. Taste bindaetteok, mayak gimbap, and more authentic Korean street food from vendors who have been serving for decades.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    price: 35,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 234,
    tags: ['HOT', 'Traditional'],
    featured: true,
  },
  {
    id: '2',
    slug: 'gangnam-korean-bbq',
    category: 'restaurants',
    subcategory: 'korean-bbq',
    city: 'seoul',
    title: 'Premium Hanwoo BBQ in Gangnam',
    description: 'Savor the finest Korean beef at a top-rated Gangnam BBQ restaurant. Includes premium Hanwoo set with all side dishes and a local dining guide.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    price: 65,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 189,
    tags: ['BEST', 'Premium'],
    featured: true,
  },
  {
    id: '3',
    slug: 'hongdae-fried-chicken',
    category: 'restaurants',
    subcategory: 'korean-fried-chicken',
    city: 'seoul',
    title: 'Hongdae Fried Chicken & Beer Night',
    description: 'Join the ultimate chimaek experience in the heart of Hongdae. Crispy Korean fried chicken paired with ice-cold Korean beer.',
    image: 'https://images.unsplash.com/photo-1575932444877-5106bee2a599?w=800&q=80',
    price: 28,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 156,
    tags: ['HOT'],
    featured: false,
  },
  {
    id: '4',
    slug: 'itaewon-cocktail-bar',
    category: 'restaurants',
    subcategory: 'bars',
    city: 'seoul',
    title: 'Hidden Speakeasy Bar in Itaewon',
    description: 'Discover Seoul\'s best-kept secret cocktail bars. Expert mixologists craft unique Korean-inspired cocktails in an intimate setting.',
    image: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80',
    price: 45,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 98,
    tags: ['NEW'],
    featured: true,
  },
  {
    id: '5',
    slug: 'gangnam-skin-clinic',
    category: 'wellness',
    subcategory: 'skin-clinic',
    city: 'seoul',
    title: 'Gangnam Premium Dermatology Clinic',
    description: 'Get world-class skin treatments at Korea\'s most renowned dermatology clinic. Consultation included with English-speaking dermatologists.',
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&q=80',
    price: 120,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 312,
    tags: ['BEST', 'Premium'],
    featured: true,
  },
  {
    id: '6',
    slug: 'hongdae-hair-salon',
    category: 'wellness',
    subcategory: 'hair-salon',
    city: 'seoul',
    title: 'K-Style Hair Makeover in Hongdae',
    description: 'Transform your look with Korea\'s trending hairstyles. Professional consultation with a celebrity hairstylist who speaks English.',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
    price: 80,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 267,
    tags: ['HOT'],
    featured: true,
  },
  {
    id: '7',
    slug: 'dragon-hill-spa',
    category: 'wellness',
    subcategory: 'sauna',
    city: 'seoul',
    title: 'Dragon Hill Spa Jjimjilbang Experience',
    description: 'The ultimate Korean spa experience. Enjoy traditional jjimjilbang with multiple sauna rooms, pools, and relaxation areas.',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80',
    price: 25,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 421,
    tags: ['Popular'],
    featured: false,
  },
  {
    id: '8',
    slug: 'bukchon-hanok-tour',
    category: 'activities',
    subcategory: 'traditional-cultural-tours',
    city: 'seoul',
    title: 'Bukchon Hanok Village Walking Tour',
    description: 'Walk through 600 years of history in this beautifully preserved traditional village. Includes hanbok rental and tea ceremony.',
    image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&q=80',
    price: 40,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 345,
    tags: ['Cultural', 'HOT'],
    featured: true,
  },
  {
    id: '9',
    slug: 'korean-cooking-class',
    category: 'activities',
    subcategory: 'cooking-classes',
    city: 'seoul',
    title: 'Learn to Make Kimchi & Bibimbap',
    description: 'Hands-on Korean cooking class in a traditional kitchen. Learn to make kimchi, bibimbap, and Korean pancakes from a local chef.',
    image: 'https://images.unsplash.com/photo-1583224994076-0a5a4e3384c7?w=800&q=80',
    price: 55,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 178,
    tags: ['BEST'],
    featured: true,
  },
  {
    id: '10',
    slug: 'haeundae-seafood',
    category: 'restaurants',
    subcategory: 'korean-food',
    city: 'busan',
    title: 'Haeundae Fresh Seafood Market Tour',
    description: 'Explore Busan\'s famous Jagalchi Fish Market and enjoy the freshest seafood in Korea. Includes sashimi set and local guide.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    price: 42,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 201,
    tags: ['HOT', 'Busan'],
    featured: true,
  },
  {
    id: '11',
    slug: 'jeju-black-pork',
    category: 'restaurants',
    subcategory: 'korean-bbq',
    city: 'jeju',
    title: 'Jeju Black Pork BBQ Experience',
    description: 'Taste Jeju\'s famous black pork at a local favorite restaurant. This unique breed is only raised on Jeju Island.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    price: 50,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 143,
    tags: ['Jeju Special'],
    featured: true,
  },
  {
    id: '12',
    slug: 'jeonju-bibimbap',
    category: 'restaurants',
    subcategory: 'korean-food',
    city: 'jeonju',
    title: 'Authentic Jeonju Bibimbap Experience',
    description: 'Taste the original bibimbap in its birthplace. Visit the best local restaurants in Jeonju Hanok Village.',
    image: 'https://images.unsplash.com/photo-1583224994076-0a5a4e3384c7?w=800&q=80',
    price: 20,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 267,
    tags: ['BEST', 'Must-Try'],
    featured: true,
  },
];
